from services.ado_client import ADOClient
from services.llm import get_llm

def run(state):
    try:
        if not state.get("branch_name"):
            state["status"] = "PR Agent skipped (no branch)"
            return state

        ado = ADOClient()
        llm = get_llm()

        # debug to check PR agent is running
        print(f"[PR Agent] Running PR Agent for build")
        print(f"[PR Agent] Branch name: {state['branch_name']}")
        print(f"[PR Agent] Repo ID: {state['repo_id']}")
        print(f"[PR Agent] Source branch: {state['source_branch']}")
        print(f"[PR Agent] Branch name: {state['branch_name']}")

        pr_title = f"Auto Fix: Build {state['build_id']} failure"
        pr_description = f"""
        Automated remediation PR.

        Root Cause:
        {state['diagnosis']['root_cause']}

        Generated by DevOps AI Agent.
        """

        pr = ado.create_pull_request(
            repository_id=state["repo_id"],
            source_branch=state["branch_name"],
            target_branch=state["source_branch"],
            title=pr_title,
            description=pr_description
        )
        
        # for debugging
        print(f"[PR Agent] PR created with ID: {pr.pull_request_id}")
        state["pr_id"] = pr.pull_request_id
        state["status"] = "PR created"

    except Exception as e:
        state["status"] = f"PR Agent failed: {str(e)}"

    return state