from services.ado_client import ADOClient

def run(state):
    try:
        if not state.get("branch_name"):
            state["status"] = "PR Agent skipped (no branch)"
            return state

        ado = ADOClient()

        pr_title = f"Auto Fix: Build {state['build_id']} failure"
        pr_description = f"""
        Automated remediation PR.

        Root Cause:
        {state.get('diagnosis', {}).get('root_cause', 'N/A')}

        Generated by DevOps AI Agent.
        """

        pr = ado.create_pull_request(
            repository_id=state["repo_id"],
            source_branch=state["branch_name"],
            target_branch=state["source_branch"],
            title=pr_title,
            description=pr_description
        )

        state["pr_id"] = pr.pull_request_id
        state["status"] = "PR created"

    except Exception as e:
        state["status"] = f"PR Agent failed: {str(e)}"

    return state